### ISSUE TITLE
Every image is converted to PNG format

### ISSUE THREAD

**Issue by craftzdog** [pi-chan/import-quiver#4]
Hi @pi-chan,

Thank you for creating the great plugin for Inkdrop!
BTW, I've got an issue with image attachments reported by a user.
It supports importing image files, which is awesome, but it always converts them into PNG format here:

https://github.com/pi-chan/import-quiver/blob/master/lib/importer.js#L120

Even if the file is just a small JPEG file, it's stored as an unnecessarily large PNG file in the Inkdrop database.
In some cases, the converted files result in larger than 10MB, which breaks the current size limit of Inkdrop.

You can determine the mime type of the file using [mime](https://github.com/broofa/mime) like so:

```js
var mime = require('mime');
mime.getType('/path/to/image.jpg');
```

Supported file types are listed here: https://github.com/inkdropapp/inkdrop-model/blob/master/src/file.js#L8
If the file type is one of them, you can simply import them with `fs.readFileSync`.

Can you please look into it?

**Comment by pi-chan** [comment]
Thanks for the report.
I've just fixed it and released the new version.

**Comment by craftzdog** [comment]
Thank you for updating it! 🙏
