### ISSUE TITLE
Support v5.5.0

### ISSUE THREAD

**Issue by craftzdog** [pi-chan/import-quiver#5]
Hi pi-chan! Thanks for creating the great plugin.
As of v5.5.0, `require('electron').remote` is no longer available.
You can use `require('@electron/remote')` instead.
Could you update it?
It's very simple like this: https://github.com/jmerle/inkdrop-tray/commit/a462082d4c4fb702facbd2ef7cf246d401aebf27

**Comment by craftzdog** [comment]
Do you have time to fix this?

**Comment by pi-chan** [comment]
Thanks for the notice.
This issue has been fixed and will be closed.

**Comment by craftzdog** [comment]
Thank you so much for the effort!
